<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Leo Alec">
<meta name="dcterms.date" content="2025-08-01">

<title>PibicFinal</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="analise_azul_trypan_files/libs/clipboard/clipboard.min.js"></script>
<script src="analise_azul_trypan_files/libs/quarto-html/quarto.js"></script>
<script src="analise_azul_trypan_files/libs/quarto-html/popper.min.js"></script>
<script src="analise_azul_trypan_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="analise_azul_trypan_files/libs/quarto-html/anchor.min.js"></script>
<link href="analise_azul_trypan_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="analise_azul_trypan_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="analise_azul_trypan_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="analise_azul_trypan_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="analise_azul_trypan_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
  
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">PibicFinal</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Leo Alec </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 1, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>pré requisitos:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"dplyr"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Anexando pacote: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Os seguintes objetos são mascarados por 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Os seguintes objetos são mascarados por 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"multcomp"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Carregando pacotes exigidos: mvtnorm</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Carregando pacotes exigidos: survival</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Carregando pacotes exigidos: TH.data</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Carregando pacotes exigidos: MASS</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Anexando pacote: 'MASS'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>O seguinte objeto é mascarado por 'package:dplyr':

    select</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Anexando pacote: 'TH.data'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>O seguinte objeto é mascarado por 'package:MASS':

    geyser</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>here() starts at C:/Users/leozi/OneDrive/Documentos/AnaliseLaboritorio</code></pre>
</div>
</div>
<ol type="1">
<li>Introdução e Preparação dos Dados</li>
</ol>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="fu">here</span>(<span class="st">"dados"</span>, <span class="st">"dados_processados.rds"</span>))</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>df_preparado <span class="ot">&lt;-</span> dados <span class="sc">%&gt;%</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Garante que não haja divisão por zero se Vivas + Mortas for 0</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Total =</span> Vivas <span class="sc">+</span> Mortas,</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calcula a proporção de células vivas (valor entre 0 e 1)</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">Proporcao_Vivas =</span> <span class="fu">ifelse</span>(Total <span class="sc">==</span> <span class="dv">0</span>, <span class="dv">0</span>, Vivas <span class="sc">/</span> Total),</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Aplica a transformação Arco-Seno da Raiz Quadrada na proporção</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Assim como muitas transformações, essa foi feita para aproximar os dados de uma distruibuição normal</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">Proporcao_Transformada =</span> <span class="fu">asin</span>(<span class="fu">sqrt</span>(Proporcao_Vivas)),</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Garante que as variáveis categóricas sejam "fatores"</span></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># E define "Controle" como o nível de referência para comparações</span></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">Sobrenadante =</span> <span class="fu">as.factor</span>(Sobrenadante),</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">Tratamento =</span> <span class="fu">factor</span>(Tratamento, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Controle"</span>, <span class="st">"Veículo"</span>, <span class="st">"1,25%"</span>, <span class="st">"10%"</span>, <span class="st">"25%"</span>))</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">head</span>(df_preparado))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>             Sobrenadante Duplicata       Data Tratamento Vivas Mortas Total
1 Lactobacillus crispatus         1 2025-04-24   Controle   188     38   226
2 Lactobacillus crispatus         1 2025-04-24    Veículo   110     38   148
3 Lactobacillus crispatus         1 2025-04-24      1,25%    91     27   118
4 Lactobacillus crispatus         1 2025-04-24        10%   134     42   176
5 Lactobacillus crispatus         1 2025-04-24        25%    45     55   100
6 Lactobacillus crispatus         1 2025-04-30   Controle   137     45   182
  Proporcao_Vivas Proporcao_Transformada
1       0.8318584              1.1482867
2       0.7432432              1.0394300
3       0.7711864              1.0720276
4       0.7613636              1.0604216
5       0.4500000              0.7353145
6       0.7527473              1.0503757</code></pre>
</div>
</div>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>df_crispatus <span class="ot">&lt;-</span> df_preparado <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Sobrenadante <span class="sc">==</span> <span class="st">"Lactobacillus crispatus"</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>df_rhamnosus <span class="ot">&lt;-</span> df_preparado <span class="sc">%&gt;%</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Sobrenadante <span class="sc">==</span> <span class="st">"Lactobacillus rhamnosus"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Para realizar uma análise estatística robusta, os dados brutos precisam ser processados. A simples contagem de células vivas pode ser enganosa, pois não leva em conta o número total de células em cada amostra. Por isso, seguimos de dois passos:</p>
<p>Cálculo da Proporção: Convertemos os dados para a proporção de células vivas (Proporcao_Vivas), que é uma métrica normalizada e justa para comparação.</p>
<p>Transformação Arco-Seno: Dados de proporção frequentemente não seguem uma distribuição normal e não possuem variâncias homogêneas, violando premissas de testes como a ANOVA. A transformação Arco-Seno da Raiz Quadrada (asin(sqrt(x))) corrige essas características, estabilizando a variância e aproximando os dados da normalidade.</p>
<ol start="2" type="1">
<li>Análise para Lactobacillus crispatus</li>
</ol>
<p>2.1 Premissas da ANOVA</p>
<p>2.1.1 Homogeneidade das variâncias - Teste de Bartlett</p>
<p>Uma das premissas da ANOVA</p>
<p>Antes de aplicar a ANOVA, precisamos verificar uma de suas principais premissas: a de que as variâncias dos diferentes grupos de tratamento são homogêneas. O Teste de Bartlett é usado para isso. A hipótese nula <span class="math inline">\(H_0\)</span> é que todas as variâncias são iguais.</p>
<p><span class="math inline">\(H_0:\)</span> As variâncias são iguais entre os grupos de tratamento.</p>
<p><span class="math inline">\(H_1:\)</span> Pelo menos um grupo tem variância diferente.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"1. Teste de Bartlett para Homogeneidade de Variâncias:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>1. Teste de Bartlett para Homogeneidade de Variâncias:</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>teste_bartlett_crispatus <span class="ot">&lt;-</span> <span class="fu">bartlett.test</span>(Proporcao_Transformada <span class="sc">~</span> Tratamento, <span class="at">data =</span> df_crispatus)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(teste_bartlett_crispatus)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Bartlett test of homogeneity of variances

data:  Proporcao_Transformada by Tratamento
Bartlett's K-squared = 3.2238, df = 4, p-value = 0.5211</code></pre>
</div>
</div>
<p>p-valor = 0.5211 | <span class="math inline">\(\alpha = 0.05\)</span>: não rejeitamos a hipótese nula. Isso significa que não há evidências para sugerir que as variâncias dos grupos sejam diferentes. Portanto, a premissa de homogeneidade da ANOVA foi atendida.</p>
<p>2.1.2. Teste de Normalidade dos Resíduos - Shapiro-Wilk</p>
<p>Agora, ajustamos o modelo ANOVA para extrair seus resíduos e verificar se eles seguem uma distribuição normal. A hipótese nula (H_0) é que os dados são normalmente distribuídos. Usamos o teste de Shapiro-Wilk para uma avaliação estatística e um gráfico Q-Q para uma inspeção visual.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Instanciando o modelo para captura dos resuduos</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>modelo_anova_crispatus <span class="ot">&lt;-</span> <span class="fu">aov</span>(Proporcao_Transformada <span class="sc">~</span> Tratamento, <span class="at">data =</span> df_crispatus)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>residuos_crispatus <span class="ot">&lt;-</span> <span class="fu">residuals</span>(modelo_anova_crispatus)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Shapiro-Wilk</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Teste de Shapiro-Wilk para Normalidade dos Resíduos:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Teste de Shapiro-Wilk para Normalidade dos Resíduos:</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>shapiro_test_crispatus <span class="ot">&lt;-</span> <span class="fu">shapiro.test</span>(residuos_crispatus)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(shapiro_test_crispatus)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  residuos_crispatus
W = 0.98156, p-value = 0.8654</code></pre>
</div>
</div>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(residuos_crispatus, <span class="at">main =</span> <span class="st">"L. crispatus - Gráfico Q-Q dos Resíduos"</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(residuos_crispatus, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analise_azul_trypan_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>O que é o Gráfico Q-Q?</p>
<p>Ao invés de plotarmos uma distribuição comum, utilizamos esse gráfico para comparar os quantis dos seus dados (dados observados) com os quantis de uma distribuição teórica perfeita, geralmente a Distribuição Normal. Quanto mais os dados seguirem a linha destacada, mais adequados estão a uma distribuição.</p>
<p>Eixo X: Os quantis teóricos. (Onde os pontos deveriam estar se seus dados seguissem perfeitamente uma distribuição normal).</p>
<p>Eixo Y: Os quantis da sua amostra de dados. (Onde seus pontos de dados realmente estão).</p>
<p>Interpretação:</p>
<p>O teste de Shapiro-Wilk resultou em um p-valor de 0.8654. Como p &gt; 0.05, não rejeitamos a hipótese nula, indicando que os resíduos do modelo são consistentes com uma distribuição normal. O gráfico Q-Q corrobora essa conclusão, pois os pontos se alinham bem ao longo da linha teórica vermelha.</p>
<p>PREMISSAS VALIDADAS</p>
<p>2.2 ANOVA</p>
<p>Este teste nos dirá se existe alguma diferença estatisticamente significativa entre as médias de pelo menos dois dos grupos de tratamento. A hipótese nula <span class="math inline">\(H_0\)</span> é que as médias de todos os grupos são iguais.</p>
<p><span class="math inline">\(H_0:\)</span> A média da proporção transformada é a mesma para todos os tratamentos</p>
<p><span class="math inline">\(H_1:\)</span> A média de pelo menos um tratamento é diferente.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Análise de Variância - ANOVA:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Análise de Variância - ANOVA:</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(modelo_anova_crispatus))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value  Pr(&gt;F)    
Tratamento   4 0.3499 0.08747      17 7.5e-07 ***
Residuals   25 0.1287 0.00515                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Interpretação:</p>
<p>p-valor = 7.5e-07 ou 0.00000075 | <span class="math inline">\(\alpha = 0.05\)</span>: rejeitamos a hipótese nula. Esta é uma forte evidência de que existe uma diferença significativa na viabilidade celular entre os grupos de tratamento para Lactobacillus crispatus.</p>
<p>2.3 Post-hoc</p>
<p>O Teste Post-Hoc de Dunnett foi aplicado para identificar quais tratamentos específicos tiveram um efeito diferente do grupo Controle.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Teste Post-Hoc de Dunnett (Comparações com o Controle):</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Teste Post-Hoc de Dunnett (Comparações com o Controle):</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>teste_dunnett_crispatus <span class="ot">&lt;-</span> <span class="fu">glht</span>(modelo_anova_crispatus, <span class="at">linfct =</span> <span class="fu">mcp</span>(<span class="at">Tratamento =</span> <span class="st">"Dunnett"</span>))</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(teste_dunnett_crispatus))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
     Simultaneous Tests for General Linear Hypotheses

Multiple Comparisons of Means: Dunnett Contrasts


Fit: aov(formula = Proporcao_Transformada ~ Tratamento, data = df_crispatus)

Linear Hypotheses:
                        Estimate Std. Error t value Pr(&gt;|t|)    
Veículo - Controle == 0 -0.04348    0.04142  -1.050  0.68047    
1,25% - Controle == 0   -0.09639    0.04142  -2.327  0.08973 .  
10% - Controle == 0     -0.14286    0.04142  -3.449  0.00717 ** 
25% - Controle == 0     -0.31230    0.04142  -7.540  &lt; 0.001 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
(Adjusted p values reported -- single-step method)</code></pre>
</div>
</div>
<p>Interpretação:</p>
<p>Veículo vs.&nbsp;Controle (p = 0.681): Não há diferença estatisticamente significativa.</p>
<p>1,25% vs.&nbsp;Controle (p = 0.090): Não há diferença estatisticamente significativa no nível de alpha=0.05.</p>
<p>10% vs.&nbsp;Controle (p = 0.007): Há uma redução estatisticamente significativa na viabilidade celular (p &lt; 0.01).</p>
<p>25% vs.&nbsp;Controle (p &lt; 0.001): Há uma redução altamente significativa na viabilidade celular.</p>
<p>Os tratamentos nas concentrações de 10% e 25% foram eficazes em reduzir a viabilidade de Lactobacillus crispatus de forma significativa quando comparados ao grupo Controle. A concentração de 1,25% e o Veículo não apresentaram efeito citotóxico. A coluna Estimate mostra valores negativos para todos, indicando que os tratamentos tenderam a reduzir a viabilidade, mas essa redução só foi estatisticamente relevante para os grupos de 10% e 25%.</p>
<ol start="3" type="1">
<li>Lactobacillus rhamnosus</li>
</ol>
<p>3.1 Premissas da ANOVA</p>
<p>3.1.1 Homogeneidade das variâncias - Teste de Bartlett</p>
<p>Primeiro, verificamos a homogeneidade das variâncias para os grupos de L. rhamnosus.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 5.1. Teste de Homogeneidade de Variâncias (Bartlett)</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Teste de Bartlett para Homogeneidade de Variâncias:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Teste de Bartlett para Homogeneidade de Variâncias:</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>teste_bartlett_rhamnosus <span class="ot">&lt;-</span> <span class="fu">bartlett.test</span>(Proporcao_Transformada <span class="sc">~</span> Tratamento, <span class="at">data =</span> df_rhamnosus)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(teste_bartlett_rhamnosus)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Bartlett test of homogeneity of variances

data:  Proporcao_Transformada by Tratamento
Bartlett's K-squared = 4.786, df = 4, p-value = 0.31</code></pre>
</div>
</div>
<p>Interpretação:</p>
<p>O Teste de Bartlett para os dados de Lactobacillus rhamnosus resultou em um p-valor de 0.31. Como este valor é consideravelmente maior que o nível de significância padrão ( alpha=0.05), não há evidências para rejeitar a hipótese nula (H_0).</p>
<p>Isso significa que podemos assumir que as variâncias dos diferentes grupos de tratamento são homogêneas (estatisticamente iguais).</p>
<p>3.1.2 Teste de Normalidade dos Resíduos - Shapiro-Wilk</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajusta o modelo para obter os resíduos</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>modelo_anova_rhamnosus <span class="ot">&lt;-</span> <span class="fu">aov</span>(Proporcao_Transformada <span class="sc">~</span> Tratamento, <span class="at">data =</span> df_rhamnosus)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>residuos_rhamnosus <span class="ot">&lt;-</span> <span class="fu">residuals</span>(modelo_anova_rhamnosus)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Teste de Shapiro-Wilk</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Teste de Shapiro-Wilk para Normalidade dos Resíduos:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Teste de Shapiro-Wilk para Normalidade dos Resíduos:</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>shapiro_test_rhamnosus <span class="ot">&lt;-</span> <span class="fu">shapiro.test</span>(residuos_rhamnosus)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(shapiro_test_rhamnosus)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  residuos_rhamnosus
W = 0.97745, p-value = 0.7546</code></pre>
</div>
</div>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Gráfico Q-Q para inspeção visual</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(residuos_rhamnosus, <span class="at">main =</span> <span class="st">"Gráfico Q-Q dos Resíduos - L. rhamnosus"</span>)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(residuos_rhamnosus, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analise_azul_trypan_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Interpretação:</p>
<p>O teste de Shapiro-Wilk resultou em um p-valor de 0.7546. Como p &gt; 0.05, não rejeitamos a hipótese nula, indicando que os resíduos do modelo são consistentes com uma distribuição normal. O gráfico Q-Q corrobora essa conclusão, pois os pontos se alinham bem ao longo da linha teórica vermelha. Ambas as premissas da ANOVA foram atendidas.</p>
<p>PREMISSAS VALIDADAS</p>
<p>3.2 ANOVA</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 5.2. Modelo ANOVA</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Análise de Variância (ANOVA):</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Análise de Variância (ANOVA):</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>modelo_anova_rhamnosus <span class="ot">&lt;-</span> <span class="fu">aov</span>(Proporcao_Transformada <span class="sc">~</span> Tratamento, <span class="at">data =</span> df_rhamnosus)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(modelo_anova_rhamnosus))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value   Pr(&gt;F)    
Tratamento   4 0.9141 0.22851   37.34 3.35e-10 ***
Residuals   25 0.1530 0.00612                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Interpretação:</p>
<p>A Análise de Variância (ANOVA) resultou em um p-valor de 3.35e-10 (ou 0.000000000335). Este valor é extraordinariamente menor que o nosso nível de significância(<span class="math inline">\(\alpha\)</span>) de 0.05. Portanto, rejeitamos a hipótese nula de que as médias são iguais. A conclusão é que há uma evidência estatística muito forte de que o tipo de tratamento tem um efeito significativo na viabilidade celular de Lactobacillus rhamnosus.</p>
<p>3.3 Post-hoc</p>
<p>Finalmente, identificamos quais tratamentos específicos diferem do Controle para esta espécie.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Post-Hoc (Comparações com o Controle):</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Post-Hoc (Comparações com o Controle):</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>teste_dunnett_rhamnosus <span class="ot">&lt;-</span> <span class="fu">glht</span>(modelo_anova_rhamnosus, <span class="at">linfct =</span> <span class="fu">mcp</span>(<span class="at">Tratamento =</span> <span class="st">"Dunnett"</span>))</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(teste_dunnett_rhamnosus))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
     Simultaneous Tests for General Linear Hypotheses

Multiple Comparisons of Means: Dunnett Contrasts


Fit: aov(formula = Proporcao_Transformada ~ Tratamento, data = df_rhamnosus)

Linear Hypotheses:
                        Estimate Std. Error t value Pr(&gt;|t|)    
Veículo - Controle == 0 -0.04348    0.04517  -0.963  0.73896    
1,25% - Controle == 0   -0.16289    0.04517  -3.607  0.00485 ** 
10% - Controle == 0     -0.27891    0.04517  -6.175  &lt; 0.001 ***
25% - Controle == 0     -0.48361    0.04517 -10.707  &lt; 0.001 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
(Adjusted p values reported -- single-step method)</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Interpretação:</p>
<p>Veículo vs.&nbsp;Controle (p = 0.739): Nenhuma diferença significativa. O veículo não afetou a viabilidade celular.</p>
<p>1,25% vs.&nbsp;Controle (p = 0.005): Há uma diferença estatisticamente significativa (p &lt; 0.01). Mesmo na menor concentração, o tratamento já reduziu a viabilidade.</p>
<p>10% vs.&nbsp;Controle (p &lt; 0.001): Há uma diferença altamente significativa.</p>
<p>25% vs.&nbsp;Controle (p &lt; 0.001): Há uma diferença altamente significativa, mostrando o efeito mais forte.</p>
<p>Para L. rhamnosus, todas as concentrações do tratamento (1,25%, 10% e 25%) foram eficazes em reduzir significativamente a viabilidade celular em comparação ao Controle. O efeito foi dose-dependente, tornando-se mais pronunciado à medida que a concentração aumentava, como pode ser visto pelo aumento do valor de t e pela diminuição do p-valor.</p>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>